import 'dotenv/config';
import OpenAI from 'openai';
import { PlanResult } from '../types';

const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) throw new Error('OPENAI_API_KEY is not set for Janus');

const openai = new OpenAI({ apiKey });

export async function codexPlan(task: string): Promise<PlanResult> {
  const sys = [
    "You are Codex-Flow, an OpenAI-based orchestrator.",
    "Given a task, you produce:",
    "1. A crisp system prompt for an implementing agent.",
    "2. A numbered implementation plan.",
    "3. A short rationale.",
    "Prefer concrete steps over fluff."
  ].join(" ");

  const res = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: sys },
      {
        role: "user",
        content: `Task: ${task}\n\nRespond in three sections labeled SYSTEM PROMPT, PLAN, RATIONALE.`
      }
    ]
  });

  const content = res.choices[0]?.message?.content ?? "";

  return {
    provider: "codex",
    systemPrompt: content,
    plan: content,
    rationale: "Codex-flow style plan generated by OpenAI."
  };
}
